apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-the-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexandrov-ua/argocd-test-cluster.git
    targetRevision: HEAD
    path: cluster
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true