apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  anotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.15.0
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastrucutre
  syncPolicy:
    syncOptions:
    - CreateNamespace=true