apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.appPort }}
        env: {{ .Values.configuration | toYaml | nindent 10 }}
        {{- if .Values.configurationSecretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.configurationSecretName }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.appPort }}
{{- if .Values.deployJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-post-deploy-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: alpine
        command: ["bin/sh", "-c", "echo hello {{ .Values.image.tag }}"]
      restartPolicy: Never
{{- end }}