apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: "charts/app-template"
    repoURL: https://github.com/alexandrov-ua/argocd-test-cluster.git
    targetRevision: HEAD
    helm:
      releaseName: nginx-app
      valuesObject:
        replicaCount: 1
        name: nginx-app
        appPort: 80
        image:
          name: nginx
          tag: 1.25.4
        configurationSecretName: nginx-app-secrets
        deployJob: true
        configuration:
        - name: NGINX_PORT
          value: "80"
        - name: asd
          value: zxc
        - name: asd1
          value: dfgdfgdfgfd

